steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mestermind-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mestermind-server:latest'
      - '-f'
      - './server/Dockerfile'
      - './server'
    dir: '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mestermind-server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mestermind-server:latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mestermind-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mestermind-server:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'  # Change to your preferred region (match your Cloud SQL instance)
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Remove if you want authenticated access only
      - '--port'
      - '8000'
      - '--max-instances'
      - '10'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:europe-west1:mestermind-db'  # Replace with your Cloud SQL instance connection name
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql+psycopg2://mestermind_user:$$DB_PASSWORD@/mestermind?host=/cloudsql/$PROJECT_ID:europe-west1:mestermind-db'
      # Note: Use --set-secrets for DB_PASSWORD instead of hardcoding
      # - '--set-secrets'
      # - 'DATABASE_URL=DATABASE_URL:latest'

images:
  - 'gcr.io/$PROJECT_ID/mestermind-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/mestermind-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

timeout: '1200s'
