version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mestermind_api
    environment:
      - DATABASE_URL=postgresql://mestermind_user:mestermind_password@postgres:5432/mestermind
      - REDIS_URL=redis://redis:6379
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - API_RELOAD=false
      - LOG_LEVEL=INFO
      - SQL_ECHO=false
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mestermind_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: mestermind_postgres
    environment:
      POSTGRES_DB: mestermind
      POSTGRES_USER: mestermind_user
      POSTGRES_PASSWORD: mestermind_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - mestermind_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mestermind_user -d mestermind"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: mestermind_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mestermind_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  mestermind_network:
    driver: bridge

